Repository google/slo-generator, pull requests merged in 2022-10, with the labels that each got.

#249 feat: add pytype linting
  Makefile
  setup.cfg
  setup.py
  slo_generator/backends/cloud_service_monitoring.py
  slo_generator/backends/datadog.py
  slo_generator/exporters/base.py
  slo_generator/migrations/migrator.py
  slo_generator/utils.py
Labels: feature

#254 tests: replace `nose` (in maintenance mode) with `pytest`
  Makefile
  setup.py
  tests/unit/test_compute.py
Labels: tests

#256 ci: run linting and unit tests on multiple python versions
  .github/workflows/test.yml
  slo_generator/report.py
  slo_generator/utils.py
Labels: ci

#261 ci: let all `lint`and `unit` jobs complete even if one fails
  .github/workflows/test.yml
Labels: ci

#245 feat: add Cloud Monitoring MQL backend
  .gitignore
  Makefile
  samples/cloud_monitoring_mql/slo_gae_app_availability.yaml
  samples/cloud_monitoring_mql/slo_gae_app_availability_ratio.yaml
  samples/cloud_monitoring_mql/slo_gae_app_latency.yaml
  samples/cloud_monitoring_mql/slo_lb_request_availability.yaml
  samples/cloud_monitoring_mql/slo_lb_request_availability_ratio.yaml
  samples/cloud_monitoring_mql/slo_lb_request_latency.yaml
  samples/cloud_monitoring_mql/slo_pubsub_subscription_throughput.yaml
  setup.py
  slo_generator/backends/cloud_monitoring.py
  slo_generator/backends/cloud_monitoring_mql.py
  slo_generator/constants.py
  slo_generator/exporters/cloud_monitoring.py
  tests/unit/backends/test_cloud_monitoring_mql.py
  tests/unit/test_stubs.py
Labels: p/cloud_monitoring, backend

#235 fix: support custom exporters
  slo_generator/utils.py
Labels: bug, exporter

#239 test: add type hints and `mypy` linting
  .gitignore
  .pylintrc
  Makefile
  mypy.ini
  setup.py
  slo_generator/api/main.py
  slo_generator/backends/cloud_monitoring.py
  slo_generator/backends/cloud_monitoring_mql.py
  slo_generator/backends/cloud_service_monitoring.py
  slo_generator/backends/elasticsearch.py
  slo_generator/backends/prometheus.py
  slo_generator/compute.py
  slo_generator/constants.py
  slo_generator/exporters/bigquery.py
  slo_generator/exporters/cloud_monitoring.py
  slo_generator/exporters/cloudevent.py
  slo_generator/exporters/prometheus_self.py
  slo_generator/exporters/pubsub.py
  slo_generator/migrations/migrator.py
  slo_generator/report.py
  slo_generator/utils.py
Labels: tests

#273 ci: increase timeout on `build` stage to account for long tests added in PR #267
  .github/workflows/deploy.yml
Labels: bug, ci

#275 docs: refine development workflow instructions
  CONTRIBUTING.md
Labels: documentation, docs

#277 docs: document Cloud Monitoring MQL backend
  docs/providers/bigquery.md
  docs/providers/cloud_monitoring.md
  docs/providers/cloud_service_monitoring.md
  docs/providers/cloudevent.md
  docs/providers/custom.md
  docs/providers/datadog.md
  docs/providers/dynatrace.md
  docs/providers/elasticsearch.md
  docs/providers/prometheus.md
  docs/providers/pubsub.md
Labels: documentation, docs, p/cloud_monitoring_mql

#280 fix: migrate `cloud_service_monitoring` backend to `google-cloud-monitoring` v2 (with breaking changes)
  slo_generator/backends/cloud_service_monitoring.py
  tests/unit/test_stubs.py
Labels: bug, tests, p/cloud_service_monitoring

#283 docs: update docs and samples with all backends
  samples/README.md
  samples/config.yaml
Labels: bug, documentation, p/dynatrace, p/datadog, docs, p/cloud_monitoring_mql

#286 Remove call to list and create metricdescriptors
  slo_generator/exporters/cloud_monitoring.py
Labels: bug, p/cloud_monitoring, exporter
