Repository google/slo-generator, pull requests merged in 2023-11, with the labels that each got.

#379 ci: build and push container images to ghcr.io too
  .github/workflows/build-and-push-to-gcr.yml
  .github/workflows/build-and-push-to-ghcr.yml
Labels: ci

#386 ci: remove warnings caused by unsupported inputs in GitHub Actions
  .github/workflows/build-and-push-to-gcr.yml
  .github/workflows/deploy.yml
Labels: bug, ci

#387 ci: use same trigger for related workflows
  .github/workflows/build-and-push-to-ghcr.yml
Labels: bug, ci

#281 ci: add Python 3.11 to linting and unit tests
  .github/workflows/test.yml
Labels: good first issue, tests, ci

#357 refactor: remove unreachable code
  slo_generator/report.py
Labels: p/datadog, refactor

#397 fix(deps): bump version of `pip` to avoid known CVE
  .github/workflows/test.yml
  setup.cfg
Labels: bug, ci

#359 refactor(tests): allow to setup the Datadog host URL
  samples/config.yaml
  tests/unit/test_stubs.py
Labels: p/datadog, backend, tests, refactor
